import { useEffect, useRef, useState, type ReactNode } from "react";
import { useApp } from "../store";
import { TTS_LOCALE } from "../i18n";

export function BigButton({ children, onClick, variant = "default", disabled, icon, ariaLabel }: { children: ReactNode; onClick?: () => void; variant?: "default" | "primary" | "danger" | "ghost"; disabled?: boolean; icon?: string; ariaLabel?: string; }) {
  return <button className={`big-btn ${variant}`} onClick={onClick} disabled={disabled} aria-label={ariaLabel}>{icon && <span className="icon" aria-hidden="true">{icon}</span>}<span>{children}</span></button>;
}
export function Spinner({ label }: { label: string }) { return <div className="spinner-wrap" role="status" aria-live="polite"><div className="spinner" aria-hidden="true" /><p>{label}</p></div>; }
export function StepProgress({ current, total }: { current: number; total: number }) { const { t } = useApp(); return <div className="progress" role="progressbar" aria-valuemin={1} aria-valuemax={total} aria-valuenow={current} aria-label={`${t("step")} ${current} ${t("of")} ${total}`}>{Array.from({ length: total }, (_, i) => <span key={i} className={i < current ? "dot on" : "dot"} />)}<span className="progress-text">{t("step")} {current} {t("of")} {total}</span></div>; }
export function ErrorBanner({ message, onRetry }: { message: string | null; onRetry?: () => void }) { const { t } = useApp(); if (!message) return null; return <div className="error" role="alert"><span aria-hidden="true">⚠️</span><p>{message}</p>{onRetry && <button className="big-btn small" onClick={onRetry}>{t("tryAgain")}</button>}</div>; }
export function ReadAloud({ text }: { text: string }) { const { t, lang } = useApp(); const [on, setOn] = useState(false); const supported = typeof window !== "undefined" && "speechSynthesis" in window; useEffect(() => () => { if (supported) window.speechSynthesis.cancel(); }, [supported]); if (!supported || !text) return null; const toggle = () => { if (on) { window.speechSynthesis.cancel(); setOn(false); return; } const u = new SpeechSynthesisUtterance(text); u.lang = TTS_LOCALE[lang]; u.onend = () => setOn(false); u.onerror = () => setOn(false); window.speechSynthesis.cancel(); window.speechSynthesis.speak(u); setOn(true); }; return <button className="big-btn small ghost" onClick={toggle}><span aria-hidden="true">{on ? "⏹" : "🔊"}</span> {on ? t("stopReading") : t("readAloud")}</button>; }

export function Shell({ title, children, back = true, speak }: { title: string; children: ReactNode; back?: boolean; speak?: string }) {
  const { t, back: goBack, session, logout, bigText, setBigText, contrast, setContrast } = useApp();
  return <div className="shell"><header>{back && <button className="nav-btn" onClick={goBack}>← {t("back")}</button>}<h1>{title}</h1><div className="tools"><button className="nav-btn" aria-pressed={bigText} onClick={() => setBigText(!bigText)}>A+</button><button className="nav-btn" aria-pressed={contrast} onClick={() => setContrast(!contrast)} aria-label={t("contrast")}>◐</button>{session && <button className="nav-btn" onClick={() => void logout()}>{t("logout")}</button>}</div></header><main>{children}{speak && <ReadAloud text={speak} />}</main></div>;
}
export function useAction<A extends unknown[], R>(fn: (...a: A) => Promise<R>) { const { errorText } = useApp(); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const alive = useRef(true); useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []); const run = async (...a: A): Promise<R | undefined> => { setBusy(true); setError(null); try { return await fn(...a); } catch (e) { if (alive.current) setError(errorText(e)); return undefined; } finally { if (alive.current) setBusy(false); } }; return { run, busy, error, setError }; }